### ISSUE TITLE
create account from mobile

### ISSUE THREAD

**Issue by sheikh-azharuddin** [passbolt/mobile-passbolt-android#3]
##IMPORTANT: PLEASE READ

## ISSUE NAME
For Android only users,there must be an option to create account either through the app itself or through mobile browser without requiring a browser extension which again need a PC.

### What you did
Tried to create account 

### What happened
It said to use browser extension 
### What you expected to happen
EXPLAIN WHAT IS TO BE EXPECTED, HERE.

**Comment by cedricalfonsi** [comment]
Thank you for your report.

If you want to discuss new features @sheikh-azharuddin , please open a topic on the [community forum](https://community.passbolt.com/c/backlog/6), the github is reserved for bugs mainly. I'm sure you will get support from other members over there.
