### ISSUE TITLE
issue in creating new account  

### ISSUE THREAD

**Issue by Rajesh88066** [passbolt/mobile-passbolt-android#6]
![Screenshot_20230529_112956](https://github.com/passbolt/mobile-passbolt-android/assets/127040535/ba00a47a-fae0-491f-a0fc-1142a0f005fa)

## login
* Passbolt Version: (c) 2021 Passbolt SA
* Platform and Target:
  projectCompileSdk = 33
    projectMinSdk = 29
    projectTargetSdk = 33

    versions = [
        androidGradlePlugin: '7.3.1',
        gradleVersionsPlugin: "0.28.0",
        desugarJdkLibs: "1.0.9",
        kotlin: "1.7.22",
        coroutines: "1.6.4",
        koin: "3.2.0",
        quadrant: "1.7",
  -android studio version 
Android Studio Flamingo | 2022.2.1 Patch 1
Build #AI-222.4459.24.2221.9971841, built on April 19, 2023
Runtime version: 17.0.6+0-b2043.56-9586694 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 12
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    gradle.version.catalogs.dynamic.support=true

### What you did 
i solved some issues relevant to sdk 

### What happened
app runs successfully but when I click on "I don't have an account" it shows me message " it is currently not possible to creating an account using the mobile app"

**Comment by cedricalfonsi** [comment]
If you want to discuss new features @Rajesh88066, please open a topic on the [community forum](https://community.passbolt.com/c/backlog/6), the github is reserved for bugs mainly.
