### ISSUE TITLE
Difficulties signing into my account for the first time

### ISSUE THREAD

**Issue by jeremyjaybaker** [passbolt/mobile-passbolt-android#7]
## ISSUE NAME
* Passbolt Version: 4.0.2-2-ce
* Platform and Target:
  -- Passbolt Android App:  1.14.0-22
  -- Android OS: Android 13
  -- Phone: Samsung Note 20 Ultra SM-N986U1
  -- Passbolt API: Not sure how to check this
  -- Other platform info: Passbolt is self-hosted, installed recently

### What you did
I tried to scan the QR code to setup my account on my mobile app 6 times.

### What happened
For the first 5 times, I got a Something Went Wrong! message and couldn't access my account. I made a 6th attempt to try and grab a screenshot of the error, but then it suddenly worked.

### What you expected to happen
I expected to be able to log into my account on the first try.

I wasn't sure whether or not to post this as I was technically able to solve my own problem here, but I figured I'd post it anyway to raise awareness of potential onboarding problems. Feel free to close this if it isn't helpful.

[Here's logs from the failed attempts](https://github.com/passbolt/mobile-passbolt-android/files/11867448/logs_24hrs.txt). Seems like the app sign in process is dependent on scanning multiple QR codes in quick succession. This is a slick solution if it works, but my phone appears to have had trouble keeping up with the changing codes.

**Comment by marcin-michalek-miquido** [comment]
Hello @jeremyjaybaker,

thanks for the feedback. From the logs, it looks like the scanning process did not start from the first QR code (`First page was not scanned, but subsequent page received`) at some point. It could be due to an initial error followed by returning to scanning without restarting the process in the web-ext. The initial error is not visible in the logs - maybe logging was not turned on at this point. We will try to reproduce the issue on our side. P.S. About the scanning in succession - this should not depend on hardware, as the mobile apps use the backend to notify the web-ext that it should "turn the QR code page", so the QR won't change unless it has been processed.

**Comment by Maazz710** [comment]
Hello,

I basically have the same issue but I'm not even able to connect to my account on the mobile App.
Here are the details of the issue:
Passbolt Version: 4.2.0
Platform and Target:
-- Passbolt Android App: 1.14.1-23
-- Android OS: Android 12
-- Phone: Fairphone 4
-- Passbolt API: Not sure how to check this
-- Other platform info: Passbolt is self-hosted

**What you did**
I tried to scan the QR code to setup my account on my mobile app without success

**What happened**
I've got an error "No internet connection"

**Troubleshooting**
Checked if I had internet access -> yes
Tried using internal Wifi, Guest Wifi, 5G -> same result
Collected debug logs from the APP
[logs_PassboltApp.txt](https://github.com/passbolt/mobile-passbolt-android/files/12546646/logs_PassboltApp.txt)

**Expected resolution**
To be able to connect to the App

Thank you for your help,
Maazz

**Comment by marcin-michalek-miquido** [comment]
Hello @Maazz710, looking at the logs the Android device cannot resolve the host.
```
Unable to resolve host: No address associated with hostname
...
android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
```
can you check your DNS config? From the logs it looks like IPv6 is used to connect - it can be a similar issue to [this one](https://github.com/passbolt/mobile-passbolt-android/issues/8#issuecomment-1694518367). You can try to disable ipv6. I believe you are not able to reach the Passbolt host even from a web browser or using a ping Android app.
